### ISSUE TITLE
link to decoder ring image is broken

### ISSUE THREAD

**Issue by radekosmulski** [earthspecies/decoder_head#1]
I tried looking at the link to figure out which image it was linking to, but didn't manage to figure this out. @aza could you please update the link or let me know which image this should be linking to and I'll fix it?

If you would like to update this yourself, please make the change in `99_index.ipynb` and run `nbdev_build_docs` from console. I think this requires having [nbdev](https://github.com/fastai/nbdev) installed.

My thinking in going for `nbdev` was that without it there is no clear way of sharing functionality between NBs which is something that we probably will need (in the past I have resolved to creating a `utils.py`  or `utils.ipynb` manually keeping it up is problematic - you need to manually copy over the new code once you make a change somewhere). Using `nbdev` we get to define functionality in one NB and import it anywhere else we need it (say for running experiments, trying out a slightly different architecture using base components, etc). Also, if we do end up developing something that others might find useful in their projects (say something for solving the linear assignment problem) this should allow us an easy way to give others an ability to use our functionality.

**Comment by aza** [comment]
Will do and super into using nbdev

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by aza** [comment]
- 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
